export const searchSuggestions = [
  "Laptop",
  "Smartphone",
  "Headphones",
  "Keyboard",
  "Mouse",
  "Monitor",
  "Accessories",
  "Gaming",
  "Software",
  "Electronics",
  "Home Appliances",
  "Furniture",
  "T-Shirts",
  "Shoes",
  "Books",
  "Sports Equipment",
  "Tablets",
  "Cameras",
  "Smartwatches",
  "Charging Cables",
  "Power Banks",
  "Office Supplies",
  "Beauty Products",
  "Health & Wellness",
  "Toys",
  "Video Games",
  "Gaming Consoles",
  "Home Decor",
  "Kitchen Appliances",
  "Vitamins",
  "Smart Home Devices",
  "Smart TVs",
  "Bluetooth Speakers",
  "Washing Machines",
  "Refrigerators",
  "Coffee Makers",
  "Air Purifiers",
  "Lawn Mowers",
  "Electric Scooters",
  "E-readers",
  "Fitness Trackers",
  "Robot Vacuums",
  "Speakers",
  "Drones",
  "Security Cameras",
  "Action Cameras",
  "Portable Speakers",
  "Projectors",
  "Car Accessories",
  "Smart Bulbs",
  "Electric Kettles",
  "Blenders",
  "Toasters",
  "Microwave Ovens",
  "Vacuum Cleaners",
  "Hair Dryers",
  "Makeup Kits",
  "Perfumes",
  "Shaving Kits",
  "Skin Care",
  "Massage Chairs",
  "Foot Massagers",
  "Body Scales",
  "Massage Guns",
  "Smart Plugs",
  "Wearable Tech",
  "Pet Supplies",
  "Food & Beverages",
  "Kitchen Tools",
  "Luggage",
  "Travel Bags",
  "Camping Gear",
  "Cycling",
  "Outdoor Furniture",
  "Yoga Mats",
  "Running Shoes",
  "Swimwear",
  "Winter Jackets",
  "Sportswear",
  "Baseball Equipment",
  "Football Gear",
  "Tennis Rackets",
  "Golf Clubs",
  "Rugby Balls",
  "Skateboards",
  "Snowboards",
  "Fishing Gear",
  "Climbing Equipment",
  "Backpacks",
  "Camping Tents",
  "Fishing Rods",
  "Sports Watches",
  "Cycling Helmets",
  "Smart Glasses",
  "Puzzles",
  "Board Games",
  "Educational Toys",
  "Legos",
  "Action Figures",
  "Dolls",
  "Remote Control Cars",
  "Play-Doh",
  "Fidget Toys",
  "Art Supplies",
  "Painting Kits",
  "Musical Instruments",
  "Guitars",
  "Keyboards",
  "Drums",
  "Violins",
  "Pianos",
  "Trumpets",
  "Saxophones",
  "Flutes",
  "Digital Cameras",
  "Lenses",
  "Tripods",
  "Camera Bags",
  "Ring Lights",
  "Drone Accessories",
  "Smartphone Cases",
  "Phone Chargers",
  "Phone Stands",
  "Screen Protectors",
  "Mobile Accessories",
  "Laptop Bags",
  "Office Chairs",
  "Desks",
  "Bookcases",
  "Lamps",
  "Desk Organizers",
  "Calendars",
  "Notebooks",
  "Pens",
  "Markers",
  "Staplers",
  "Paper Clips",
  "File Folders",
  "Laptop Stands",
  "Whiteboards",
  "Projector Screens",
  "Smart Thermostats",
  "Electric Fans",
  "Space Heaters",
  "Dehumidifiers",
  "Water Purifiers",
  "Humidifiers",
  "Electric Blankets",
  "Heated Mattress Pads",
  "Air Conditioners",
  "Portable Air Conditioners",
  "Garage Tools",
  "Power Tools",
  "Drills",
  "Screwdrivers",
  "Hammers",
  "Pliers",
  "Ladders",
  "Chainsaws",
  "Saws",
  "Paint Brushes",
  "Lawn Care Products",
  "Shovels",
  "Rakes",
  "Hoses",
  "Snow Shovels",
  "Gardening Tools",
  "Plant Pots",
  "Seeds",
  "Soil",
  "Fertilizers",
  "Landscaping Rocks",
  "Bird Feeders",
  "Compost Bins",
  "Greenhouses",
  "Hydroponics Kits",
  "Aquarium Supplies",
  "Pet Food",
  "Pet Beds",
  "Pet Toys",
  "Dog Leashes",
  "Cat Trees",
  "Pet Grooming",
  "Fish Tanks",
  "Bird Cages",
  "Reptile Tanks",
  "Pet Health",
  "Pet Medications",
];
